-- SOLUTION 1

SELECT 
    sell_date,
    COUNT(DISTINCT product) AS num_sold, -- DISTINCT PRODUCTS BECAUSE THERE ARE DUPLICATES IN THE TABLE AND WE DON'T WANT TO COUNT SAME PRODUCT MULTIPLE TIMES
    GROUP_CONCAT(DISTINCT product) AS products -- WHEN WE WANT TO CONCATENATE STRINGS FROM A GROUP INTO A SINGLE STRING WITH VARIOUS OPTION, WE USE GROUP_CONCAT
FROM
    activities
GROUP BY sell_date;